
import { Button, HorizontalBox,VerticalBox } from "std-widgets.slint";
import { TabWidget, ComboBox } from "std-widgets.slint";
export component LeftTab {
   // property<color> c1: #ff00ee;
    Rectangle {
       // background: c1;
    width:100%;
    height: 100%;
            Rectangle {
     //           background: c1;
                min-height: 200px;
                width:100%;

            VerticalBox {
                Button {    text:"Crea una Nuova Sessione" ; }
                Button {    text:"Cancella sessione" ; }
                Text {    text:"Sessione:" ; }
                ComboBox {
                    model:      ["Session | 05-03-2024 10:35"];
                    current-value:    "Session | 05-03-2024 10:35";
                }
                    Rectangle {}
                }
            }
        
        
}
    }
