
import { Button, HorizontalBox,VerticalBox } from "std-widgets.slint";
import { TabWidget } from "std-widgets.slint";
export component LeftTab3 {
    Rectangle {
        height: 150px;
        padding: 10px;
        VerticalBox {
            Text {           text: "";}
            Text {           text: "Dati delle sessione";}
            Text {           text: "Nome";}
            Text {           text: "Session del None";}
            Text {           text: "File:";}
            Text {           text: "VOC (|type|, ßocc): (?,?)";}
            Text {           text: "Multi-core:";}
            Text {           text: "OFF";}
        }
    
    }
    }

