import { Button, HorizontalBox,VerticalBox } from "std-widgets.slint";
import { MyTopMenu} from "topmenu/topmenu.slint";
import { Right } from "right/right.slint";
import { Left } from "left/left.slint";
import { MyContent } from "content.slint";
import { MyTopMenuFile } from "topmenu/topmenu_file.slint";
import { MyTopMenuAnalisi } from "topmenu/topmenu_analisi.slint";
import { MyTopMenuImpostationi } from "topmenu/topmenu_impostationi.slint";
import { MyTopMenuInfo } from "topmenu/topmenu_info.slint";

/*

MenuItem := Rectangle {
    property <string> name;
    // You can add more UI definitions here
}
*/
export component AppWindow inherits Window {
  //in-out property <model> menu_items;
//  property <model> menu_items: [];
  //     property <[MenuItem]> menu_items: [];
        callback request-increase-value();
    preferred-height: 600px;
    preferred-width: 1000px;
    VerticalLayout {
          HorizontalLayout {
          height: 30px;  
          alignment: start;
          z: 10;
            MyTopMenuFile { }

            MyTopMenuAnalisi {
  
            }
            MyTopMenuImpostationi {
  
            }
            MyTopMenuInfo {
  
            }
        }

        
        MyContent {
           // y: 100px;
        }
    
  }
}
