
import { Button, HorizontalBox,VerticalBox } from "std-widgets.slint";
import { Left } from "left/left.slint";
import { Right } from "right/right.slint";
import { TabWidget, ComboBox } from "std-widgets.slint";
export component MyContent {
  //  property <color> c2: #000ddd;
    Rectangle {
        width: parent.width - 20px;
        height: parent.height - 20px;
        padding: 10px; 
        y: 10px;
        
        TabWidget {
            padding: 10px;
            Tab {
                padding: 20px;
                title: "Sessioni";
              //  property<color> c2: #ff0000;
                Rectangle {
                //    background: c2;
                    min-height: 200px;
                    HorizontalLayout {
                        Left {
                            
                            height: 100%;width: 310px;
                        }
                        Right {}
                    }
                
                }    
            }
            Tab {
                title: "Risorse";
                Rectangle {
                    min-height: 200px;width:100%;
                    background: green; }
            }
            Tab {
                title: "Mie Risorse";
                Rectangle {
                    min-height: 200px;width:100%;
                    background: pink; }
            }
        }
        
        
        
        
    }
}
